# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballotmeasure',
            name='election',
        ),
        migrations.AddField(
            model_name='ballotmeasure',
            name='election_day',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='election.ElectionDay'),
            preserve_default=False,
        ),
    ]
