# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name_plural': 'Parties'},
        ),
        migrations.AddField(
            model_name='candidate',
            name='elections',
            field=models.ManyToManyField(related_name='candidates', to='election.Election'),
        ),
        migrations.AlterField(
            model_name='ballotmeasure',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballot_measures', to='geography.Division'),
        ),
        migrations.AlterField(
            model_name='ballotmeasure',
            name='election_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballot_measures', to='election.ElectionDay'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='election.Party'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='entity.Person'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='election.Race'),
        ),
        migrations.AlterField(
            model_name='election',
            name='election_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elections', to='election.ElectionType'),
        ),
        migrations.AlterField(
            model_name='election',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='election.Party'),
        ),
        migrations.AlterField(
            model_name='electionday',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elections_days', to='election.ElectionCycle'),
        ),
        migrations.AlterField(
            model_name='race',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='election.ElectionCycle'),
        ),
        migrations.AlterField(
            model_name='race',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='entity.Office'),
        ),
    ]
