# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateElection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregable', models.BooleanField(default=True)),
                ('uncontested', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='aggregable',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='elections',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='uncontested',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='winner',
        ),
        migrations.AddField(
            model_name='candidateelection',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Candidate'),
        ),
        migrations.AddField(
            model_name='candidateelection',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Election'),
        ),
        migrations.AddField(
            model_name='election',
            name='candidates',
            field=models.ManyToManyField(through='election.CandidateElection', to='election.Candidate'),
        ),
        migrations.AlterUniqueTogether(
            name='candidateelection',
            unique_together=set([('candidate', 'election')]),
        ),
    ]
