# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_auto_20171024_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='label',
        ),
        migrations.RemoveField(
            model_name='election',
            name='name',
        ),
        migrations.RemoveField(
            model_name='election',
            name='short_label',
        ),
        migrations.RemoveField(
            model_name='election',
            name='slug',
        ),
    ]
