# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_remove_candidate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='electiontype',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electiontype',
            name='number_of_winners',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='electiontype',
            name='primary_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='electiontype',
            name='winning_threshold',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
