# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_auto_20171024_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electiontype',
            name='ap_code',
            field=models.CharField(max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='ap_code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
