# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_auto_20171024_1617'),
        ('election', '0002_auto_20171023_1907'),
    ]

    operations = [
    ]
