# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('geography', '0001_initial'),
        ('election', '0003_auto_20171031_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=500)),
                ('chatter', models.TextField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geography.Division')),
                ('election_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.ElectionDay')),
            ],
        ),
    ]
