# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 15:22
from __future__ import unicode_literals

import core.aws
from django.db import migrations, models
import django.db.models.deletion
import theshow.models.person_image
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('election', '0004_remove_candidate_image'),
        ('geography', '0001_initial'),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=500)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geography.Division')),
                ('election_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.ElectionDay')),
            ],
        ),
        migrations.CreateModel(
            name='PageContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PageContentType',
            fields=[
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tag', models.SlugField(help_text='Used to serialize images. <b>Must be unique per person.</b>')),
                ('image', models.ImageField(storage=core.aws.StorageService(), upload_to=theshow.models.person_image.person_image_path)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='entity.Person')),
            ],
        ),
        migrations.AddField(
            model_name='pagecontentblock',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='theshow.PageContentType'),
        ),
        migrations.AddField(
            model_name='pagecontentblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='theshow.PageContent'),
        ),
        migrations.AlterUniqueTogether(
            name='personimage',
            unique_together=set([('person', 'tag')]),
        ),
        migrations.AlterUniqueTogether(
            name='pagecontentblock',
            unique_together=set([('page', 'content_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='pagecontent',
            unique_together=set([('content_type', 'object_id', 'election_day', 'division')]),
        ),
    ]
