# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theshow', '0002_auto_20171110_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetype',
            name='body',
            field=models.ForeignKey(blank=True, help_text='Only set body for senate/house pages', null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Body'),
        ),
        migrations.AlterField(
            model_name='pagetype',
            name='jurisdiction',
            field=models.ForeignKey(blank=True, help_text='Only set jurisdiction for federal pages', null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Jurisdiction'),
        ),
        migrations.AlterField(
            model_name='pagetype',
            name='office',
            field=models.ForeignKey(blank=True, help_text='Only set office for the presidency', null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Office'),
        ),
    ]
