# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20171031_1554'),
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegates',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='delegates',
            name='election',
        ),
        migrations.RemoveField(
            model_name='electoralvotes',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='electoralvotes',
            name='election',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='election',
        ),
        migrations.AddField(
            model_name='delegates',
            name='candidate_election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegates', to='election.CandidateElection'),
        ),
        migrations.AddField(
            model_name='electoralvotes',
            name='candidate_election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electoral_votes', to='election.CandidateElection'),
        ),
        migrations.AddField(
            model_name='votes',
            name='candidate_election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='election.CandidateElection'),
        ),
    ]
