# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegates',
            name='total',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='electoralvotes',
            name='total',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='votes',
            name='total',
            field=models.PositiveIntegerField(),
        ),
    ]
