# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20171031_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delegates',
            options={'verbose_name_plural': 'Delegates'},
        ),
        migrations.AlterModelOptions(
            name='electoralvotes',
            options={'verbose_name_plural': 'Electoral Votes'},
        ),
        migrations.AlterModelOptions(
            name='votes',
            options={'verbose_name_plural': 'Votes'},
        ),
        migrations.AlterField(
            model_name='delegates',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electoralvotes',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='votes',
            name='ballot_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='election.BallotAnswer'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
