# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20171018_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegates',
            name='total',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='electoralvotes',
            name='total',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='votes',
            name='total',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
