# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20171102_1301'),
        ('vote', '0003_auto_20171101_1535'),
    ]

    operations = [
    ]
