# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 19:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('short_label', models.CharField(blank=True, max_length=50, null=True)),
                ('effective', models.BooleanField(default=True)),
                ('effective_start', models.DateTimeField(null=True)),
                ('effective_end', models.DateTimeField(null=True)),
                ('code', models.CharField(help_text='Code representing a geography: FIPS code for states and         counties, district number for districts, precinct number for         precincts, etc.', max_length=200)),
                ('code_components', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Component parts of code', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DivisionLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='geography.DivisionLevel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective', models.BooleanField(default=True)),
                ('effective_start', models.DateTimeField(null=True)),
                ('effective_end', models.DateTimeField(null=True)),
                ('simplification', models.FloatField(help_text='Minimum quantile of planar         triangle areas for simplfying topojson.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('topojson', django.contrib.postgres.fields.jsonb.JSONField()),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geographies', to='geography.Division')),
                ('subdivision_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geography.DivisionLevel')),
            ],
            options={
                'verbose_name_plural': 'Geographies',
            },
        ),
        migrations.AddField(
            model_name='division',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.DivisionLevel'),
        ),
        migrations.AddField(
            model_name='division',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='geography.Division'),
        ),
    ]
