# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 21:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intersection', models.DecimalField(blank=True, decimal_places=6, help_text='The portion of the to_division that intersects the from_division.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
        ),
        migrations.AlterField(
            model_name='division',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='geography.Division'),
        ),
        migrations.AlterField(
            model_name='divisionlevel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='geography.DivisionLevel'),
        ),
        migrations.AddField(
            model_name='peerrelationship',
            name='from_division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='geography.Division'),
        ),
        migrations.AddField(
            model_name='peerrelationship',
            name='to_division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='geography.Division'),
        ),
        migrations.AddField(
            model_name='division',
            name='peers',
            field=models.ManyToManyField(help_text='Peers represent geographic divisions that intersect but do not necessarily have a parent/child relationship. The relationship between a congressional district and a precinct is an example of a peer relationship.', related_name='_division_peers_+', through='geography.PeerRelationship', to='geography.Division'),
        ),
        migrations.AlterUniqueTogether(
            name='peerrelationship',
            unique_together=set([('from_division', 'to_division')]),
        ),
    ]
