# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0003_auto_20171018_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='geography.DivisionLevel'),
        ),
        migrations.AlterField(
            model_name='intersectrelationship',
            name='intersection',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='The portion of the to_division that intersects this division.', max_digits=7, null=True),
        ),
    ]
