# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0004_auto_20171018_2004'),
        ('geography', '0004_auto_20171018_1611'),
    ]

    operations = [
    ]
