# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_auto_20171017_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
