# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_auto_20171018_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
