# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_auto_20171018_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Body'),
        ),
        migrations.AlterField(
            model_name='office',
            name='jurisdiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Jurisdiction'),
        ),
    ]
