# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0005_auto_20171023_1907'),
        ('entity', '0006_auto_20171024_1414'),
    ]

    operations = [
    ]
